### ISSUE TITLE
[PE-D] Command Summary Format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-2/tp#136]
![Screenshot 2021-10-29 at 4.47.07 PM.png](https://raw.githubusercontent.com/EuniceSim142/ped/main/files/26dd7051-42b9-4955-b683-273847ddbfea.png)

* Command Summary formatting is wrong. 
* Some commands are not even used in the application (e.g. count)
* The prefixes are all wrong (e.g. -n instead of n/)
* Some prefixes are not used (e.g. -s)

This can inconvenience many users.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: EuniceSim142/ped#5

**Comment by bryanwee023** [comment]
Fixed in user guide update.
