### ISSUE TITLE
[PE-D] Documentation issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-2/tp#144]
![image.png](https://raw.githubusercontent.com/leonghongfai/ped/main/files/d9ea098e-0ddd-4dc8-9c29-f4a8d7f0792a.png)

list command should not belong here, since it takes in parameters, and list123 is not interpreted as list

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: leonghongfai/ped#13

**Comment by bryanwee023** [comment]
Fixed in user guide update.
