### ISSUE TITLE
[PE-D] Parameters formatting is inconsistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-2/tp#148]
![Screenshot 2021-10-29 at 5.14.27 PM.png](https://raw.githubusercontent.com/EuniceSim142/ped/main/files/cf19cdc2-b17b-4955-aeb5-cc9aeb16ee75.png)

![Screenshot 2021-10-29 at 5.14.18 PM.png](https://raw.githubusercontent.com/EuniceSim142/ped/main/files/82fa80c5-4510-4a77-8b82-7a39fda1160a.png)

![Screenshot 2021-10-29 at 5.23.37 PM.png](https://raw.githubusercontent.com/EuniceSim142/ped/main/files/d4dcac7f-f5f3-43b7-aeb2-d228f489b635.png)

![Screenshot 2021-10-29 at 6.05.26 PM.png](https://raw.githubusercontent.com/EuniceSim142/ped/main/files/0ae3ef8c-1f3b-45c0-aad5-bbba082e8c87.png)

If you specified id/{id_number} in the command format notes, you should use the same snake case format for all the command formats. <br>
You should also use the same parameter name, unless ambiguous.
(e.g. can use index as long as its obvious what the `index` is referring to. If need to provide both order and item index in 1 command, then you should use `order_index` and `item_index`)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: EuniceSim142/ped#8

**Comment by bryanwee023** [comment]
The formatting has been specified in the user guide update.
