### ISSUE TITLE
[PE-D] Sort item by id feature does not exist.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-2/tp#162]
The application does not recognise the command to sort or list by id as stated in the User Guide.

![Screenshot 2021-10-29 at 4.34.29 PM.png](https://raw.githubusercontent.com/boonhaii/ped/main/files/2dc1e7ac-df25-440e-a920-9222eb2d252d.png)

![Screenshot 2021-10-29 at 4.35.02 PM.png](https://raw.githubusercontent.com/boonhaii/ped/main/files/e79754ca-94c8-4b7e-8333-795abadcc282.png)

![Screenshot 2021-10-29 at 4.35.59 PM.png](https://raw.githubusercontent.com/boonhaii/ped/main/files/5370bb54-6b7d-478b-bb13-08ac5a4b514b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: boonhaii/ped#4

**Comment by bryanwee023** [comment]
See #111.
